title: Site

options:
  changeTitle: false

tabs:
  content:
    label: Content
    icon: window

    columns:
      main:
        width: 1/4

        sections:
          published:
            headline: Link categories
            type: pages
            status: listed
            templates: category
          drafts:
            headline: Draft categories
            type: pages
            status: draft
            templates: category

      theme:
        width: 1/2

        fields:
          activetheme:
            width: 1/2
            label: Color theme
            help: Default is Dark space
            type: select
            options:
              type: query
              query: page('themes').children.filterBy('intendedTemplate', 'in', ['theme', 'theme-locked'])
              text: '{{ page.title }}'
              value: '{{ page.slug }}'

          logo:
            width: 1/2
            label: Logo style
            type: select
            default: script
            help: Default is script
            options:
              script: Script (default)
              angular: Angular
              brush: Brush
              icon: Icon
              inverse: Inverse
              pixel: Pixel
              rounded: Rounded

          fontfamily:
            width: 1/2
            label: Font
            type: select
            default: system
            help: Default is System
            options:
              udon_mono: Udon mono
              inter: Inter
              bitter: Bitter
              fira_mono: Fira Mono
              fira_sans: Fira Sans
              lora: Lora
              newsreader: Newsreader
              offside: Offside
              plex_mono: Plex Mono
              plex_sans: Plex Sans
              plex_serif: Plex Serif
              roboto_condensed: Roboto Condensed
              roboto_slab: Roboto Slab
              source_serif_pro: Source Serif Pro
              space_mono: Space Mono
              system: System default
              turret_road: Turret Road
              ubuntu: Ubuntu
              work_sans: Work Sans

          fontsize:
            width: 1/2
            label: Font size
            help: Default is 1.0 rem
            type: range
            step: 0.05
            min: 0.5
            max: 1.25
            default: 1.0
            after: rem

          linespacing:
            width: 1/2
            label: Line spacing
            help: Default is 1.9 rem
            type: range
            step: 0.1
            min: 1
            max: 2.2
            default: 1.9
            after: rem

          letterspacing:
            width: 1/2
            label: Letter spacing
            help: Default is 0 px
            type: range
            step: 0.1
            min: -1
            max: 1
            default: 0
            after: px

      other:
        width: 1/4
        fields:
          passwordprotected:
            label: Protect with password
            type: toggle
            text:
              - 'no'
              - 'yes'
            help: If set to yes, the page is only available to logged-in users. Logged-out users will be redirected to the panel log-in page.

  # themes tab
  themes:
    label: Themes
    icon: brush

    sections:
      themepages:
        type: pages
        label: All themes
        headline: All themes
        parent: page('themes')
        templates:
          - theme
          - theme-locked
        create: theme
