title: Site

tabs:

  # content tab
  links:
    label: Links
    icon: text

    sections:

      # draft categories
      drafts:
        headline: Draft categories
        type: pages
        status: draft
        templates: category

      # visible categories
      published:
        headline: Visible categories
        type: pages
        status: listed
        templates: category

  # other tab
  other:
    label: Other content
    icon: template

    sections:

      # unlisted content
      unlisted:
        headline: Unlisted pages
        type: pages
        status: unlisted

  # settings tab
  settings:
    label: Bentobox settings
    icon: settings

    settings:
    type: fields

    fields:

      theme:
        width: 1/3
        label: Theme
        type: select
        default: dark-sea
        options:
          air: Air
          amber: Amber
          club: Club
          dark-sea: Dark Sea
          dark-space: Dark Space
          glow-stick: Glow Stick
          jade: Jade
          lakeshore: Lake Shore
          light-lunch: Light Lunch
          minty: Minty
          ocean-lights: Ocean Lights
          red-sun: Red Sun
          retro-neon: Retro Neon
          rs-green: RS Green
          sci-fi: Sci-fi
          shaped: Shaped
          summer-night: Summer Night

      logo:
        width: 1/3
        label: Logo style
        type: select
        default: script
        options:
          script: Script (default)
          angular: Angular
          brush: Brush
          icon: Icon
          inverse: Inverse
          pixel: Pixel
          rounded: Rounded

      fontfamily:
        width: 1/3
        label: Font
        type: select
        default: system
        options:
          bitter: Bitter
          fira_mono: Fira Mono
          fira_sans: Fira Sans
          lora: Lora
          newsreader: Newsreader
          offside: Offside
          plex_mono: Plex Mono
          plex_sans: Plex Sans
          plex_serif: Plex Serif
          roboto_condensed: Roboto Condensed
          roboto_slab: Roboto Slab
          source_serif_pro: Source Serif Pro
          space_mono: Space Mono
          system: System default
          turret_road: Turret Road
          ubuntu: Ubuntu
          work_sans: Work Sans

      fontsize:
        width: 1/3
        label: Font size
        help: Default is 1.0 rem
        type: range
        step: 0.05
        min: 0.75
        max: 1.25
        default: 1.0
        after: rem

      linespacing:
        width: 1/3
        label: Line spacing
        help: Default is 1.9 rem
        type: range
        step: 0.1
        min: 1.2
        max: 2.2
        default: 1.9
        after: rem

      letterspacing:
        width: 1/3
        label: Letter spacing
        help: Default is 0 px
        type: range
        step: 0.1
        min: -1
        max: 1
        default: 0
        after: px
